# Generated by Django 6.0.5 on 2026-07-04 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0010_placementtestsettings_remove_class_is_public_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="placement_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="academy.placementtestrequest",
                verbose_name="Placement Test Request",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="class_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="academy.class",
            ),
        ),
    ]
