# Generated by Django 6.0.5 on 2026-07-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_invoice_placement_request_alter_invoice_class_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated tax amount', max_digits=10),
        ),
    ]
