# Generated by Django 5.2.5 on 2025-10-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
