# Generated by Django 6.0.5 on 2026-05-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="host",
        ),
        migrations.RemoveField(
            model_name="room",
            name="topic",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
