# Generated by Django 5.2.5 on 2026-05-29 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_code',
            field=models.PositiveBigIntegerField(blank=True, help_text='Unique numeric code in the format YYYYMMNNN (e.g., 140308001)', null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)], verbose_name='Class Code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('EDU_MGR', 'Education Manager'), ('SENIOR_MGR', 'Senior Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
    ]
