# Generated by Django 6.0.5 on 2026-05-31 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0002_class_class_code_alter_employee_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="day_of_week",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Days of the week (0=Monday, 1=Tuesday, 2=Wednesday, 3=Thursday, 4=Friday, 5=Saturday, 6=Sunday). Example: [0, 2]",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="End time"),
        ),
        migrations.AddField(
            model_name="class",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Start time"),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("is_cancelled", models.BooleanField(default=False)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="academy.class",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
                "unique_together": {("class_group", "date", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Present"),
                            ("A", "Absent"),
                            ("L", "Late"),
                            ("E", "Excused"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="academy.student",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="academy.session",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "student")},
            },
        ),
    ]
