# Generated by Django 6.0.5 on 2026-06-09 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0003_class_day_of_week_class_end_time_class_start_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacementTestRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("IN_PERSON", "In-Person Test"),
                            ("PREV_GRADE", "Previous Term Grade"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "requested_level",
                    models.CharField(
                        blank=True,
                        help_text="Self-assessed Level (optional)",
                        max_length=20,
                    ),
                ),
                (
                    "approved_level",
                    models.CharField(
                        blank=True, help_text="Level assigned by manager", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("PARTIAL", "Partial"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_requests",
                        to="academy.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
