# Generated by Django 6.0.5 on 2026-06-12 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0005_alter_employee_position_exam_examsection_oralgrade_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="Created_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="is_finalized",
        ),
        migrations.AddField(
            model_name="exam",
            name="exam_date",
            field=models.DateField(blank=True, null=True, verbose_name="Exam Date"),
        ),
        migrations.AddField(
            model_name="exam",
            name="status",
            field=models.CharField(
                choices=[("OPEN", "Open for Grading"), ("FINALIZED", "Finalized")],
                default="OPEN",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="finalized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finalized_exams",
                to="academy.employee",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="total_score",
            field=models.PositiveIntegerField(default=300),
        ),
    ]
