# Generated by Django 6.0.5 on 2026-06-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0006_rename_created_at_exam_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="tuition_fee",
            field=models.PositiveIntegerField(default=0, verbose_name="Tuition Fee"),
        ),
    ]
