# Generated by Django 6.0.5 on 2026-07-02 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0007_class_tuition_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="class_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="academy.class",
                verbose_name="Class",
            ),
        ),
    ]
