# Generated by Django 6.0.5 on 2026-07-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0008_alter_exam_class_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="Public Class"),
        ),
    ]
