# Generated by Django 6.0.5 on 2026-07-04 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0009_class_is_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacementTestSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_fee",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Placement Test Fee"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="class",
            name="is_public",
        ),
        migrations.AddField(
            model_name="placementtestrequest",
            name="test_date",
            field=models.DateField(blank=True, null=True, verbose_name="Test Date"),
        ),
        migrations.AddField(
            model_name="placementtestrequest",
            name="test_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Test Time"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="class_group",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam",
                to="academy.class",
            ),
            preserve_default=False,
        ),
    ]
