# Generated by Django 6.0.5 on 2026-07-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_transferrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage (e.g., 9 for 9%)', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
